server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/musicdb
    username: music
    password: music
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

jwt:
  secret: docker-secret-key
  expiration: 3600000

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: music-files

